on:
  workflow_call:
    inputs:
      db_url:
        required: true
        type: string
      host:
        required: true
        type: string
    secrets:
      VERCEL_TOKEN:
        required: true

jobs:
  migrate_and_deploy_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Prisma Migrate
        run: |
          touch .env
          echo DATABASE_URL=${DATABASE_URL} >> .env
          echo SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL} >> .env
          npx prisma migrate dev
        env:
          DATABASE_URL: ${{ inputs.db_url}}/neondb
          SHADOW_DATABASE_URL: ${{ inputs.db_url}}/shadowdb
      - name: Deploy to Vercel
        id: deploy
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          preview_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "preview_url=${preview_url}" >> $GITHUB_OUTPUT
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Neon Branch Host :elephant: : ${{ inputs.host }}
            Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}
